ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - command: >
      curl -fsSL https://deno.land/x/install/install.sh | sh &&
      export DENO_INSTALL="/home/gitpod/.deno" &&
      export PATH="$DENO_INSTALL/bin:$PATH" &&
      deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -f https://deno.land/x/deploy/deployctl.ts &&
      cd /workspace &&
      deployctl run --watch --no-check ./main.tsx
vscode:
  extensions:
    - denoland.vscode-deno@3.2.0:Uwf/jB20dfIdQC0JrEprsw==